// Spell data
var ALL_SPELLS = [
  // ABJURATION
  { name: "Absorb Elements", level: 1, school: "Abjuration" },
  { name: "Alarm", level: 1, school: "Abjuration" },
  { name: "Mage Armor", level: 1, school: "Abjuration" },
  { name: "Protection from Evil and Good", level: 1, school: "Abjuration" },
  { name: "Shield", level: 1, school: "Abjuration" },
  { name: "Snare", level: 1, school: "Abjuration" },
  { name: "Wardaway", level: 1, school: "Abjuration" },

  { name: "Arcane Lock", level: 2, school: "Abjuration" },
  { name: "Arcane Vigor", level: 2, school: "Abjuration" },
  { name: "Elminster's Elusion", level: 2, school: "Abjuration" },
  { name: "Sanguine Shield", level: 2, school: "Abjuration" },
  { name: "Nondetection", level: 2, school: "Abjuration" },

  { name: "Counterspell", level: 3, school: "Abjuration" },
  { name: "Dispel Magic", level: 3, school: "Abjuration" },
  { name: "Glyph of Warding", level: 3, school: "Abjuration" },
  { name: "Intellect Fortress", level: 3, school: "Abjuration" },
  { name: "Magic Circle", level: 3, school: "Abjuration" },
  { name: "Stoneskin", level: 3, school: "Abjuration" },
  { name: "Protection from Energy", level: 3, school: "Abjuration" },
  { name: "Remove Curse", level: 3, school: "Abjuration" },

  { name: "Backlash", level: 4, school: "Abjuration" },
  { name: "Banishment", level: 4, school: "Abjuration" },
  { name: "Gate Seal", level: 4, school: "Abjuration" },
  { name: "Mordenkainen's Private Sanctum", level: 4, school: "Abjuration" },
  { name: "Otiluke's Resilient Sphere", level: 4, school: "Abjuration" },

  { name: "Alustriel's Mooncloak", level: 5, school: "Abjuration" },
  { name: "Circle of Power", level: 5, school: "Abjuration" },
  { name: "Mirrored Agony", level: 5, school: "Abjuration" },
  { name: "Planar Binding", level: 5, school: "Abjuration" },
  { name: "Guards and Wards", level: 5, school: "Abjuration" },

  { name: "Contingency", level: 6, school: "Abjuration" },
  { name: "Fizban's Platinum Shield", level: 6, school: "Abjuration" },
  { name: "Globe of Invulnerability", level: 6, school: "Abjuration" },

  { name: "Symbol", level: 7, school: "Abjuration" },
  { name: "Mind Blank", level: 7, school: "Abjuration" },

  { name: "Antimagic Field", level: 8, school: "Abjuration" },
  { name: "Imprisonment", level: 8, school: "Abjuration" },

  { name: "Invulnerability", level: 9, school: "Abjuration" },
  { name: "Prismatic Wall", level: 9, school: "Abjuration" },

  // CONJURATION
  { name: "Find Familiar", level: 1, school: "Conjuration" },
  { name: "Fog Cloud", level: 1, school: "Conjuration" },
  { name: "Grease", level: 1, school: "Conjuration" },
  { name: "Ice Knife", level: 1, school: "Conjuration" },
  { name: "Tenser's Floating Disk", level: 1, school: "Conjuration" },
  { name: "Unseen Servant", level: 1, school: "Conjuration" },

  { name: "Air Bubble", level: 2, school: "Conjuration" },
  { name: "Cloud of Daggers", level: 2, school: "Conjuration" },
  { name: "Dust Devil", level: 2, school: "Conjuration" },
  { name: "Deryan's Helpful Homunculi", level: 2, school: "Conjuration" },
  { name: "Flaming Sphere", level: 2, school: "Conjuration" },
  { name: "Flock of Familiars", level: 2, school: "Conjuration" },
  { name: "Spray of Cards", level: 2, school: "Conjuration" },
  { name: "Misty Step", level: 2, school: "Conjuration" },
  { name: "Vortex Warp", level: 2, school: "Conjuration" },
  { name: "Web", level: 2, school: "Conjuration" },

  { name: "Conjure Constructs", level: 3, school: "Conjuration" },
  { name: "Galder's Tower", level: 3, school: "Conjuration" },
  { name: "Sleet Storm", level: 3, school: "Conjuration" },
  { name: "Stinking Cloud", level: 3, school: "Conjuration" },
  { name: "Summon Fey", level: 3, school: "Conjuration" },
  { name: "Summon Lesser Demons", level: 3, school: "Conjuration" },
  { name: "Summon Shadowspawn", level: 3, school: "Conjuration" },
  { name: "Syluné's Viper", level: 3, school: "Conjuration" },
  { name: "Thunder Step", level: 3, school: "Conjuration" },
  { name: "Tidal Wave", level: 3, school: "Conjuration" },

  { name: "Dimension Door", level: 4, school: "Conjuration" },
  { name: "Evard's Black Tentacles", level: 4, school: "Conjuration" },
  { name: "Galder's Speedy Courier", level: 4, school: "Conjuration" },
  { name: "Leomund's Secret Chest", level: 4, school: "Conjuration" },
  { name: "Mordenkainen's Faithful Hound", level: 4, school: "Conjuration" },
  { name: "Ride the Lightning", level: 4, school: "Conjuration" },
  { name: "Summon Aberration", level: 4, school: "Conjuration" },
  { name: "Summon Construct", level: 4, school: "Conjuration" },
  { name: "Summon Elemental", level: 4, school: "Conjuration" },
  { name: "Watery Sphere", level: 4, school: "Conjuration" },

  { name: "Cloudkill", level: 5, school: "Conjuration" },
  { name: "Conjure Elemental", level: 5, school: "Conjuration" },
  { name: "Far Step", level: 5, school: "Conjuration" },
  { name: "Infernal Calling", level: 5, school: "Conjuration" },
  { name: "Steel Wind Strike", level: 5, school: "Conjuration" },
  { name: "Summon Draconic Spirit", level: 5, school: "Conjuration" },
  { name: "Summon Dragon", level: 5, school: "Conjuration"},
  { name: "Summon Greater Demon", level: 5, school: "Conjuration" },

  { name: "Arcane Gate", level: 6, school: "Conjuration" },
  { name: "Blood Tide", level: 6, school: "Conjuration" },
  { name: "Drawmij's Instant Summons", level: 6, school: "Conjuration" },
  { name: "Scatter", level: 6, school: "Conjuration" },
  { name: "Summon Fiend", level: 6, school: "Conjuration" },
  { name: "Tasha's Bubbling Cauldron", level: 6, school: "Conjuration" },

  { name: "Burst Forth", level: 7, school: "Conjuration" },
  { name: "Dream of the Blue Veil", level: 7, school: "Conjuration" },
  { name: "Conjure Shadow Titan", level: 7, school: "Conjuration" },
  { name: "Chains of Beleth", level: 7, school: "Conjuration" },
  { name: "Mordenkainen's Magnificent Mansion", level: 7, school: "Conjuration" },
  { name: "Etherealness", level: 7, school: "Conjuration" },
  { name: "Plane Shift", level: 7, school: "Conjuration" },
  { name: "Teleport", level: 7, school: "Conjuration" },

  { name: "Demiplane", level: 8, school: "Conjuration" },
  { name: "Incendiary Cloud", level: 8, school: "Conjuration" },
  { name: "Maze", level: 8, school: "Conjuration" },
  { name: "Mighty Fortress", level: 8, school: "Conjuration" },
  { name: "Wall of Gloom", level: 8, school: "Conjuration" },

  { name: "Blade of Disaster", level: 9, school: "Conjuration" },
  { name: "Gate", level: 9, school: "Conjuration" },
  { name: "Wish", level: 9, school: "Conjuration" },

  // DIVINATION
  { name: "Binding Pledge", level: 1, school: "Divination" },
  { name: "Comprehend Languages", level: 1, school: "Divination" },
  { name: "Detect Magic", level: 1, school: "Divination" },
  { name: "Identify", level: 1, school: "Divination" },

  { name: "Augury", level: 2, school: "Divination" },
  { name: "Borrowed Knowledge", level: 2, school: "Divination" },
  { name: "Detect Thoughts", level: 2, school: "Divination" },
  { name: "Locate Object", level: 2, school: "Divination" },
  { name: "Mind Spike", level: 2, school: "Divination" },
  { name: "See Invisibility", level: 2, school: "Divination" },
  { name: "Warp Sense", level: 2, school: "Divination" },

  { name: "Clairvoyance", level: 3, school: "Divination" },
  { name: "Sending", level: 3, school: "Divination" },
  { name: "Tongues", level: 3, school: "Divination" },

  { name: "Arcane Eye", level: 4, school: "Divination" },
  { name: "Divination", level: 4, school: "Divination" },
  { name: "Locate Creature", level: 4, school: "Divination" },
  { name: "Rary's Telepathic Bond", level: 4, school: "Divination" },
  { name: "Telepathic Bond", level: 4, school: "Divination" },

  { name: "Contact Other Plane", level: 5, school: "Divination" },
  { name: "Legend Lore", level: 5, school: "Divination" },
  { name: "Scrying", level: 5, school: "Divination" },

  { name: "True Seeing", level: 6, school: "Divination" },

  { name: "Telepathy", level: 8, school: "Divination" },

  { name: "Foresight", level: 9, school: "Divination" },

  // ENCHANTMENT
  { name: "Charm Person", level: 1, school: "Enchantment" },
  { name: "Hideous Laughter", level: 1, school: "Enchantment" },
  { name: "Sleep", level: 1, school: "Enchantment" },
  { name: "Tasha's Hideous Laughter", level: 1, school: "Enchantment" },

  { name: "Crown of Madness", level: 2, school: "Enchantment" },
  { name: "Gift of Gab", level: 2, school: "Enchantment" },
  { name: "Hold Person", level: 2, school: "Enchantment" },
  { name: "Jim's Glowing Coin", level: 2, school: "Enchantment" },
  { name: "Suggestion", level: 2, school: "Enchantment" },
  { name: "Tasha's Mind Whip", level: 2, school: "Enchantment" },

  { name: "Antagonize", level: 3, school: "Enchantment" },
  { name: "Catnap", level: 3, school: "Enchantment" },
  { name: "Curse of Fastidious Pride", level: 3, school: "Enchantment" },
  { name: "Curse of Ravenous Hunger", level: 3, school: "Enchantment" },
  { name: "Enemies Abound", level: 3, school: "Enchantment" },
  { name: "Fast Friends", level: 3, school: "Enchantment" },
  { name: "Incite Greed", level: 3, school: "Enchantment" },

  { name: "Charm Monster", level: 4, school: "Enchantment" },
  { name: "Confusion", level: 4, school: "Enchantment" },
  { name: "Curse of Lost Sentiment", level: 4, school: "Enchantment" },
  { name: "Raulothim's Psychic Lance", level: 4, school: "Enchantment" },

  { name: "Curse of Insatiable Greed", level: 5, school: "Enchantment" },
  { name: "Dominate Person", level: 5, school: "Enchantment" },
  { name: "Geas", level: 5, school: "Enchantment" },
  { name: "Hold Monster", level: 5, school: "Enchantment" },
  { name: "Incite Riot", level: 5, school: "Enchantment" },
  { name: "Modify Memory", level: 5, school: "Enchantment" },

  { name: "Curse of Conceited Obsession", level: 6, school: "Enchantment" },
  { name: "Curse of Crushing Sensation", level: 6, school: "Enchantment" },
  { name: "Curse of Uncontrollable Wrath", level: 6, school: "Enchantment" },
  { name: "Mass Suggestion", level: 6, school: "Enchantment" },
  { name: "Otto's Irresistible Dance", level: 6, school: "Enchantment" },

  { name: "Power Word Maim", level: 7, school: "Enchantment" },
  { name: "Power Word Pain", level: 7, school: "Enchantment" },

  { name: "Antipathy/Sympathy", level: 8, school: "Enchantment" },
  { name: "Befuddlement", level: 8, school: "Enchantment" },
  { name: "Dominate Monster", level: 8, school: "Enchantment" },
  { name: "Feeblemind", level: 8, school: "Enchantment" },
  { name: "Power Word Stun", level: 8, school: "Enchantment" },
  { name: "Synaptic Static", level: 8, school: "Enchantment" },
  { name: "Yolande's Regal Presence", level: 8, school: "Enchantment" },

  { name: "Power Word Kill", level: 9, school: "Enchantment" },
  { name: "Psychic Scream", level: 9, school: "Enchantment" },

  // EVOCATION
  { name: "Burning Hands", level: 1, school: "Evocation" },
  { name: "Chromatic Orb", level: 1, school: "Evocation" },
  { name: "Consumption", level: 1, school: "Evocation" },
  { name: "Earth Tremor", level: 1, school: "Evocation" },
  { name: "Frost Fingers", level: 1, school: "Evocation" },
  { name: "Ghost Light", level: 1, school: "Evocation" },
  { name: "Jim's Magic Missile", level: 1, school: "Evocation" },
  { name: "Magic Missile", level: 1, school: "Evocation" },
  { name: "Spellfire Flare", level: 1, school: "Evocation" },
  { name: "Tasha's Caustic Brew", level: 1, school: "Evocation" },
  { name: "Thunderwave", level: 1, school: "Evocation" },
  { name: "Tremor", level: 1, school: "Evocation" },
  { name: "Vibrating Humors", level: 1, school: "Evocation" },
  { name: "Witch Bolt", level: 1, school: "Evocation" },

  { name: "Aganazzar's Scorcher", level: 2, school: "Evocation" },
  { name: "Blood Wisp", level: 2, school: "Evocation" },
  { name: "Continual Flame", level: 2, school: "Evocation" },
  { name: "Darkness", level: 2, school: "Evocation" },
  { name: "Dazing Blast", level: 2, school: "Evocation" },
  { name: "Gust of Wind", level: 2, school: "Evocation" },
  { name: "Melf's Acid Arrow", level: 2, school: "Evocation" },
  { name: "Rime's Binding Ice", level: 2, school: "Evocation" },
  { name: "Shatter", level: 2, school: "Evocation" },
  { name: "Snilloc's Snowball Swarm", level: 2, school: "Evocation" },
  { name: "Warding Wind", level: 2, school: "Evocation" },

  { name: "Cacophonic Shield", level: 3, school: "Evocation" },
  { name: "Fireball", level: 3, school: "Evocation" },
  { name: "Laeral's Silver Lance", level: 3, school: "Evocation" },
  { name: "Leomund's Tiny Hut", level: 3, school: "Evocation" },
  { name: "Lightning Bolt", level: 3, school: "Evocation" },
  { name: "Melf's Minute Meteors", level: 3, school: "Evocation" },
  { name: "Sending (2014)", level: 3, school: "Evocation" },
  { name: "Wall of Sand", level: 3, school: "Evocation" },
  { name: "Wall of Water", level: 3, school: "Evocation" },

  { name: "Fire Shield", level: 4, school: "Evocation" },
  { name: "Ice Storm", level: 4, school: "Evocation" },
  { name: "Otiluke's Resilient Sphere (2014)", level: 4, school: "Evocation" },
  { name: "Sickening Radiance", level: 4, school: "Evocation" },
  { name: "Spellfire Storm", level: 4, school: "Evocation" },
  { name: "Storm Sphere", level: 4, school: "Evocation" },
  { name: "Vitriolic Sphere", level: 4, school: "Evocation" },
  { name: "Wall of Fire", level: 4, school: "Evocation" },

  { name: "Bigby's Hand", level: 5, school: "Evocation" },
  { name: "Cone of Cold", level: 5, school: "Evocation" },
  { name: "Dawn", level: 5, school: "Evocation" },
  { name: "Immolation", level: 5, school: "Evocation" },
  { name: "Jallarzi's Storm of Radiance", level: 5, school: "Evocation" },
  { name: "Wall of Force", level: 5, school: "Evocation" },
  { name: "Wall of Light", level: 5, school: "Evocation" },
  { name: "Wall of Stone", level: 5, school: "Evocation" },

  { name: "Chain Lightning", level: 6, school: "Evocation" },
  { name: "Contingency (2014)", level: 6, school: "Evocation" },
  { name: "Elminster's Effulgent Spheres", level: 6, school: "Evocation" },
  { name: "Heartseeker", level: 6, school: "Evocation" },
  { name: "Otiluke's Freezing Sphere", level: 6, school: "Evocation" },
  { name: "Sunbeam", level: 6, school: "Evocation" },
  { name: "Wall of Ice", level: 6, school: "Evocation" },

  { name: "Crown of Stars", level: 7, school: "Evocation" },
  { name: "Delayed Blast Fireball", level: 7, school: "Evocation" },
  { name: "Forcecage", level: 7, school: "Evocation" },
  { name: "Mordenkainen's Sword", level: 7, school: "Evocation" },
  { name: "Prismatic Spray", level: 7, school: "Evocation" },
  { name: "Sanguine Fusillade", level: 7, school: "Evocation" },
  { name: "Whirlwind", level: 7, school: "Evocation" },

  { name: "Holy Star of Mystra", level: 8, school: "Evocation" },
  { name: "Maddening Darkness", level: 8, school: "Evocation" },
  { name: "Sunburst", level: 8, school: "Evocation" },
  { name: "Telepathy (2014)", level: 8, school: "Evocation" },

  { name: "Meteor Swarm", level: 9, school: "Evocation" },

  // ILLUSION
  { name: "Color Spray", level: 1, school: "Illusion" },
  { name: "Disguise Self", level: 1, school: "Illusion" },
  { name: "Distort Value", level: 1, school: "Illusion" },
  { name: "Illusory Script", level: 1, school: "Illusion" },
  { name: "Silent Image", level: 1, school: "Illusion" },

  { name: "Arcanist's Magic Aura", level: 2, school: "Illusion" },
  { name: "Blur", level: 2, school: "Illusion" },
  { name: "Invisibility", level: 2, school: "Illusion" },
  { name: "Magic Mouth", level: 2, school: "Illusion" },
  { name: "Mirror Image", level: 2, school: "Illusion" },
  { name: "Nathair's Mischief", level: 2, school: "Illusion" },
  { name: "Nystul's Magic Aura", level: 2, school: "Illusion" },
  { name: "Phantasmal Force", level: 2, school: "Illusion" },
  { name: "Shadow Blade", level: 2, school: "Illusion" },

  { name: "Fear", level: 3, school: "Illusion" },
  { name: "Hypnotic Pattern", level: 3, school: "Illusion" },
  { name: "Major Image", level: 3, school: "Illusion" },
  { name: "Phantom Steed", level: 3, school: "Illusion" },

  { name: "Greater Invisibility", level: 4, school: "Illusion" },
  { name: "Hallucinatory Terrain", level: 4, school: "Illusion" },
  { name: "Phantasmal Killer", level: 4, school: "Illusion" },
  { name: "Seeming", level: 4, school: "Illusion" },

  { name: "Creation", level: 5, school: "Illusion" },
  { name: "Dream", level: 5, school: "Illusion" },
  { name: "Mislead", level: 5, school: "Illusion" },

  { name: "Mental Prison", level: 6, school: "Illusion" },
  { name: "Programmed Illusion", level: 6, school: "Illusion" },

  { name: "Mirage Arcane", level: 7, school: "Illusion" },
  { name: "Project Image", level: 7, school: "Illusion" },
  { name: "Simulacrum", level: 7, school: "Illusion" },

  { name: "Illusory Dragon", level: 8, school: "Illusion" },

  { name: "Weird", level: 9, school: "Illusion" },

  // NECROMANCY
  { name: "Cause Fear", level: 1, school: "Necromancy" },
  { name: "False Life", level: 1, school: "Necromancy" },
  { name: "Ray of Sickness", level: 1, school: "Necromancy" },

  { name: "Blindness/Deafness", level: 2, school: "Necromancy" },
  { name: "Bloat", level: 2, school: "Necromancy" },
  { name: "Blood Sacrifice", level: 2, school: "Necromancy" },
  { name: "Chorus of the Lost", level: 2, school: "Necromancy" },
  { name: "Death Armor", level: 2, school: "Necromancy" },
  { name: "Gentle Repose", level: 2, school: "Necromancy" },
  { name: "Life Tether", level: 2, school: "Necromancy" },
  { name: "Ray of Enfeeblement", level: 2, school: "Necromancy" },
  { name: "Wither and Bloom", level: 2, school: "Necromancy" },

  { name: "Animate Dead", level: 3, school: "Necromancy" },
  { name: "Bestow Curse", level: 3, school: "Necromancy" },
  { name: "Crimson Harvest", level: 3, school: "Necromancy"},
  { name: "Feign Death", level: 3, school: "Necromancy" },
  { name: "Life Transference", level: 3, school: "Necromancy" },
  { name: "Speak with Dead", level: 3, school: "Necromancy" },
  { name: "Spirit Shroud", level: 3, school: "Necromancy" },
  { name: "Summon Undead", level: 3, school: "Necromancy" },
  { name: "Vampiric Touch", level: 3, school: "Necromancy" },

  { name: "Blight", level: 4, school: "Necromancy" },
  { name: "Consume Mind", level: 4, school: "Necromancy" },
  { name: "Curse of Damned Aging", level: 4, school: "Necromancy" },
  { name: "Curse of Foul Blight", level: 4, school: "Necromancy" },
  { name: "Spirit of Death", level: 4, school: "Necromancy" },
  { name: "Viscous Sheath", level: 4, school: "Necromancy" },
  { name: "Wall of Death", level: 4, school: "Necromancy" },

  { name: "Danse Macabre", level: 5, school: "Necromancy" },
  { name: "Enervation", level: 5, school: "Necromancy" },
  { name: "Greater Animate Dead", level: 5, school: "Necromancy" },
  { name: "Negative Energy Flood", level: 5, school: "Necromancy" },
  { name: "Spirit Swarm", level: 5, school: "Necromancy" },

  { name: "Black Well", level: 6, school: "Necromancy" },
  { name: "Circle of Death", level: 6, school: "Necromancy" },
  { name: "Create Undead", level: 6, school: "Necromancy" },
  { name: "Eyebite", level: 6, school: "Necromancy" },
  { name: "Magic Jar", level: 6, school: "Necromancy" },
  { name: "Soul Cage", level: 6, school: "Necromancy" },

  { name: "Finger of Death", level: 7, school: "Necromancy" },
  { name: "Fleshcrawl", level: 7, school: "Necromancy" },
  { name: "Undead Enthrallment", level: 7, school: "Necromancy" },

  { name: "Abi-Dalzim's Horrid Wilting", level: 8, school: "Necromancy" },
  { name: "Clone", level: 8, school: "Necromancy" },
  { name: "Creeping Death", level: 8, school: "Necromancy" },
  { name: "Flense", level: 8, school: "Necromancy" },
  { name: "Lifesink", level: 8, school: "Necromancy" },

  { name: "Astral Projection", level: 9, school: "Necromancy" },
  { name: "Wipe Face", level: 9, school: "Necromancy" },

  // TRANSMUTATION
  { name: "Catapult", level: 1, school: "Transmutation" },
  { name: "Creeping Touch", level: 1, school: "Transmutation" },
  { name: "Expeditious Retreat", level: 1, school: "Transmutation" },
  { name: "Feather Fall", level: 1, school: "Transmutation" },
  { name: "Jump", level: 1, school: "Transmutation" },
  { name: "Longstrider", level: 1, school: "Transmutation" },
  { name: "Vampiric Claws", level: 1, school: "Transmutation" },

  { name: "Alter Self", level: 2, school: "Transmutation" },
  { name: "Blindness/Deafness", level: 2, school: "Transmutation" },
  { name: "Darkvision", level: 2, school: "Transmutation" },
  { name: "Dragon's Breath", level: 2, school: "Transmutation" },
  { name: "Earthbind", level: 2, school: "Transmutation" },
  { name: "Enhance Ability", level: 2, school: "Transmutation" },
  { name: "Enlarge/Reduce", level: 2, school: "Transmutation" },
  { name: "Fiend Flesh", level: 2, school: "Transmutation" },
  { name: "Kinetic Jaunt", level: 2, school: "Transmutation" },
  { name: "Knock", level: 2, school: "Transmutation" },
  { name: "Levitate", level: 2, school: "Transmutation" },
  { name: "Magic Weapon", level: 2, school: "Transmutation" },
  { name: "Maximilian's Earthen Grasp", level: 2, school: "Transmutation" },
  { name: "Pyrotechnics", level: 2, school: "Transmutation" },
  { name: "Rope Trick", level: 2, school: "Transmutation" },
  { name: "Skywrite", level: 2, school: "Transmutation" },
  { name: "Spider Climb", level: 2, school: "Transmutation" },
  { name: "Theft of Vitae", level: 2, school: "Transmutation" },

  { name: "Ashardalon's Stride", level: 3, school: "Transmutation" },
  { name: "Blink", level: 3, school: "Transmutation" },
  { name: "Call the Rabid Beast", level: 3, school: "Transmutation" },
  { name: "Emmeline's Essence Infusion", level: 3, school: "Transmutation" },
  { name: "Erupting Earth", level: 3, school: "Transmutation" },
  { name: "Extract Iron", level: 3, school: "Transmutation" },
  { name: "Flame Arrows", level: 3, school: "Transmutation" },
  { name: "Fly", level: 3, school: "Transmutation" },
  { name: "Gaseous Form", level: 3, school: "Transmutation" },
  { name: "Haste", level: 3, school: "Transmutation" },
  { name: "Serpent Tongue", level: 3, school: "Transmutation" },
  { name: "Slow", level: 3, school: "Transmutation" },
  { name: "Tiny Servant", level: 3, school: "Transmutation" },
  { name: "Water Breathing", level: 3, school: "Transmutation" },

  { name: "Buried Alive", level: 4, school: "Transmutation" },
  { name: "Control Water", level: 4, school: "Transmutation" },
  { name: "Elemental Bane", level: 4, school: "Transmutation" },
  { name: "Fabricate", level: 4, school: "Transmutation" },
  { name: "Polymorph", level: 4, school: "Transmutation" },
  { name: "Stone Shape", level: 4, school: "Transmutation" },
  { name: "Stoneskin", level: 4, school: "Transmutation" },
  { name: "Transmute Rock", level: 4, school: "Transmutation" },

  { name: "Animate Objects", level: 5, school: "Transmutation" },
  { name: "Control Winds", level: 5, school: "Transmutation" },
  { name: "Create Spelljamming Helm", level: 5, school: "Transmutation" },
  { name: "Passwall", level: 5, school: "Transmutation" },
  { name: "Skill Empowerment", level: 5, school: "Transmutation" },
  { name: "Songal's Elemental Suffusion", level: 5, school: "Transmutation" },
  { name: "Telekinesis", level: 5, school: "Transmutation" },

  { name: "Create Homunculus", level: 6, school: "Transmutation" },
  { name: "Disintegrate", level: 6, school: "Transmutation" },
  { name: "Earth Worm", level: 6, school: "Transmutation" },
  { name: "Flesh to Stone", level: 6, school: "Transmutation" },
  { name: "Investiture of Flame", level: 6, school: "Transmutation" },
  { name: "Investiture of Ice", level: 6, school: "Transmutation" },
  { name: "Investiture of Stone", level: 6, school: "Transmutation" },
  { name: "Investiture of Wind", level: 6, school: "Transmutation" },
  { name: "Melting Curse", level: 6, school: "Transmutation" },
  { name: "Move Earth", level: 6, school: "Transmutation" },
  { name: "Tasha's Otherworldly Guise", level: 6, school: "Transmutation" },
  { name: "Tenser's Transformation", level: 6, school: "Transmutation" },

  { name: "Create Magen", level: 7, school: "Transmutation" },
  { name: "Draconic Transformation", level: 7, school: "Transmutation" },
  { name: "Etherealness", level: 7, school: "Transmutation" },
  { name: "Reverse Gravity", level: 7, school: "Transmutation" },
  { name: "Sequester", level: 7, school: "Transmutation" },
  { name: "Simbul's Synostodweomer", level: 7, school: "Transmutation" },

  { name: "Control Weather", level: 8, school: "Transmutation" },

  { name: "Mass Polymorph", level: 9, school: "Transmutation" },
  { name: "Shapechange", level: 9, school: "Transmutation" },
  { name: "Time Stop", level: 9, school: "Transmutation" },
  { name: "True Polymorph", level: 9, school: "Transmutation" }
];